language: node_js

node_js:
  - "0.10"

before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - curl -L http://git.io/ejPSng | /bin/sh