language: node_js

node_js:
  - "0.10"

cache:
  directories:
    - $HOME/.meteor
    - $HOME/.npm

before_cache:
  - rm -f $HOME/.meteor/log/*.log

before_install:
  # Download Meteor - Keep in mind that you need
  # to remove your travis cache to get meteor updates
  - PATH=$PATH:$HOME/.meteor
  - if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi
  - meteor npm install --save bcrypt